apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-practice-eks
  region: us-east-1

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: main-ng
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    privateNetworking: false
