apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
  namespace: {{ .Values.namespace }}
  labels: 
    {{- include "go-api.labels" . | nindent 4 }}

data:
  APP_ENV: "{{ .Values.appConfig.APP_ENV }}"
  APP_PORT: "{{ .Values.appConfig.APP_PORT }}"
