apiVersion: v1
kind: Secret
metadata:
  name: go-api-secret
  namespace: {{ .Values.namespace  }}
  labels:
    {{- include "go-api.labels" . | nindent 4 }}
  
type: Opaque
data:
  DB_PASSWORD: c3VwZXJzZWNyZXQxMjM=
